### ISSUE TITLE
Cant import automatone to my project

### ISSUE THREAD

**Issue by d4annn** [Ladysnake/Automatone#5]
Im trying to import automatone to my minecraft mod but i cant find any way to do it. 
`modImplementation urlFile("src/lib/automatone-0.9.1", 'automatone-0.9.1', "1.20.1")` <-- i implement it in this way

this is the method:
`def urlFile = { url, name, version ->
	File file = new File("$rootDir/lib/${name}-${version}.jar")
	file.parentFile.mkdirs()
	if (!file.exists()) {
		new URL(url).withInputStream { downloadStream ->
			file.withOutputStream { fileOut ->
				fileOut << downloadStream
			}
		}
	}
	return [name: name, version: version]
}`
![image](https://github.com/Ladysnake/Automatone/assets/93409970/a54097a9-e27c-483f-80ba-8312f15db51f)

**Comment by Pyrofab** [comment]
Uuuh, yeah I guess that's on me for not giving instructions. You should first add our repository to your `repositories` section in `build.gradle` (create it if it does not exist) :
```gradle
repositories {
        maven { repo ->
            repo.name = "Ladysnake Mods"
            repo.setUrl("https://maven.ladysnake.org/releases")
        }
}
```
then add it to your dependencies :
```gradle
modImplementation("io.github.ladysnake:automatone:0.9.1")
```

However, note that the latest version is not for 1.20.1 yet.
